apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: platform-demo
  namespace: platform-demo
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: platform-demo.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: platform-demo
                port:
                  number: 80
